export type Tool = {
  name: string
  description: string
  url: string
  tags: string[]
  score: number
  logoUrl?: string
}

export type Category = {
  slug: string
  label: string
  desc: string
  group: "people" | "teams"
  count: number
  tools: Tool[]
}

export const CATEGORIES: Category[] = [
  // ── FOR PEOPLE ──────────────────────────────────────────────────────────────
  {
    slug: "general-purpose-ai-agents",
    label: "General-Purpose AI Agents",
    desc: "AI agents that can browse the web, manage files, run code, and take autonomous action — across any domain.",
    group: "people",
    count: 9,
    tools: [
      { name: "AutoGPT", description: "Open-source autonomous AI agent that chains GPT-4 calls to complete long-horizon tasks without human intervention.", url: "https://agpt.co", tags: ["Open Source", "Autonomous", "GPT-4"], score: 34, logoUrl: "https://agpt.co/favicon.ico" },
      { name: "AgentGPT", description: "Browser-based autonomous AI that lets you configure and deploy AI agents directly from your browser with no coding required.", url: "https://agentgpt.reworkd.ai", tags: ["No-code", "Browser", "Autonomous"], score: 30, logoUrl: "https://agentgpt.reworkd.ai/favicon.ico" },
      { name: "SuperAGI", description: "Developer-first autonomous AI agent framework with a GUI, multiple agent support, and a marketplace of tools and capabilities.", url: "https://superagi.com", tags: ["Open Source", "Framework", "Multi-agent"], score: 32, logoUrl: "https://superagi.com/favicon.ico" },
      { name: "OpenAgents", description: "Open platform for deploying language agents in the wild with web browsing, code execution, and plugin support.", url: "https://github.com/xlang-ai/OpenAgents", tags: ["Open Source", "Research", "Plugins"], score: 28, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
      { name: "Devin", description: "The first AI software engineer — plans and executes multi-step engineering tasks, writes code, runs tests, and ships features.", url: "https://devin.ai", tags: ["Coding", "Autonomous", "SWE"], score: 36, logoUrl: "https://devin.ai/favicon.ico" },
      { name: "GPT Engineer", description: "One-prompt codebase generator — describe your app and GPT Engineer builds the entire codebase autonomously.", url: "https://gptengineer.app", tags: ["Coding", "Open Source", "One-shot"], score: 31, logoUrl: "https://gptengineer.app/favicon.ico" },
      { name: "BabyAGI", description: "Lightweight autonomous task-management AI that creates, prioritizes, and executes tasks toward a given goal.", url: "https://github.com/yoheinakajima/babyagi", tags: ["Open Source", "Research", "Task management"], score: 26, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
      { name: "Adept AI", description: "Action-oriented AI that understands software UIs and takes real actions inside enterprise applications on your behalf.", url: "https://adept.ai", tags: ["Enterprise", "UI actions", "Autonomous"], score: 33, logoUrl: "https://adept.ai/favicon.ico" },
    ],
  },
  {
    slug: "coding-agents",
    label: "Coding Agents",
    desc: "AI that writes, reviews, debugs, and ships code — from single functions to full features.",
    group: "people",
    count: 18,
    tools: [
      { name: "GitHub Copilot", description: "AI pair programmer from GitHub and OpenAI. Suggests code completions, generates functions, and explains code right inside your editor.", url: "https://github.com/features/copilot", tags: ["IDE", "Completions", "Enterprise"], score: 35, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
      { name: "Cursor", description: "AI-first code editor built on VS Code with multi-file edits, codebase-aware chat, and autonomous PR-level changes.", url: "https://cursor.sh", tags: ["Editor", "Multi-file", "Codebase"], score: 36, logoUrl: "https://cursor.sh/brand/icon.svg" },
      { name: "Aider", description: "AI pair programming in your terminal — edits multiple files, writes tests, and commits changes using GPT-4 or Claude.", url: "https://aider.chat", tags: ["Terminal", "Open Source", "Multi-file"], score: 33, logoUrl: "https://aider.chat/assets/icons/aider.svg" },
      { name: "Sweep", description: "AI junior developer that turns GitHub issues into pull requests automatically, writing and testing code end-to-end.", url: "https://sweep.dev", tags: ["GitHub", "PRs", "Autonomous"], score: 32, logoUrl: "https://sweep.dev/favicon.ico" },
      { name: "Cody by Sourcegraph", description: "Code AI with full codebase context — finds references, explains complex code, and generates new code aware of your entire repo.", url: "https://sourcegraph.com/cody", tags: ["Codebase", "Context", "Enterprise"], score: 34 },
      { name: "Continue", description: "Open-source AI code assistant that works in VS Code and JetBrains, supporting any LLM including local models.", url: "https://continue.dev", tags: ["Open Source", "Any LLM", "IDE"], score: 31, logoUrl: "https://continue.dev/favicon.ico" },
      { name: "Tabnine", description: "AI code assistant focused on privacy and security — runs models locally or on private cloud, ideal for regulated industries.", url: "https://tabnine.com", tags: ["Privacy", "Local", "Enterprise"], score: 30 },
      { name: "Replit AI", description: "AI built into Replit's browser-based IDE — generates apps from prompts, fixes bugs, and explains code in real time.", url: "https://replit.com", tags: ["Browser IDE", "No-setup", "Full-stack"], score: 32 },
    ],
  },
  {
    slug: "personal-assistants",
    label: "Personal Assistants",
    desc: "General-purpose AI assistants for everyday tasks, scheduling, research, and personal productivity.",
    group: "people",
    count: 9,
    tools: [
      { name: "ChatGPT", description: "OpenAI's flagship AI assistant with GPT-4o — handles writing, research, coding, image generation, voice, and web browsing.", url: "https://chat.openai.com", tags: ["General", "Multimodal", "Plugins"], score: 36, logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/120px-ChatGPT_logo.svg.png" },
      { name: "Claude", description: "Anthropic's AI assistant with a 200K-token context window — excels at long-document analysis, nuanced reasoning, and coding.", url: "https://claude.ai", tags: ["Long context", "Reasoning", "Safety"], score: 36, logoUrl: "https://claude.ai/favicon.ico" },
      { name: "Gemini", description: "Google's multimodal AI assistant deeply integrated with Google Workspace — Docs, Drive, Gmail, and Search.", url: "https://gemini.google.com", tags: ["Google", "Multimodal", "Workspace"], score: 35, logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Google_Gemini_logo.svg/120px-Google_Gemini_logo.svg.png" },
      { name: "Perplexity AI", description: "AI-powered search and answer engine that cites sources in real time — great for research and staying current.", url: "https://perplexity.ai", tags: ["Search", "Citations", "Real-time"], score: 34, logoUrl: "https://www.perplexity.ai/favicon.ico" },
      { name: "Notion AI", description: "AI built into Notion that writes, edits, summarizes, and auto-fills databases inside your existing workspace.", url: "https://notion.so/product/ai", tags: ["Productivity", "Notes", "Workspace"], score: 32 },
      { name: "Mem AI", description: "Self-organizing AI notes app that surfaces relevant memories and context automatically as you work.", url: "https://mem.ai", tags: ["Notes", "Memory", "Context"], score: 30, logoUrl: "https://mem.ai/favicon.ico" },
      { name: "Pi by Inflection", description: "Personal AI companion focused on emotional intelligence, active listening, and thoughtful conversation.", url: "https://pi.ai", tags: ["Companion", "EQ", "Conversational"], score: 29, logoUrl: "https://pi.ai/favicon.ico" },
      { name: "Otter.ai", description: "AI meeting assistant that transcribes, summarizes, and generates action items from conversations in real time.", url: "https://otter.ai", tags: ["Meetings", "Transcription", "Summary"], score: 31 },
    ],
  },
  {
    slug: "writing-creativity",
    label: "Writing & Creativity",
    desc: "AI tools built primarily for writing, content creation, copywriting, and creative work.",
    group: "people",
    count: 14,
    tools: [
      { name: "Jasper", description: "Enterprise AI writing platform for marketing teams — generates on-brand blog posts, ads, emails, and social content at scale.", url: "https://jasper.ai", tags: ["Marketing", "Brand voice", "Enterprise"], score: 34 },
      { name: "Copy.ai", description: "AI copywriting tool with 90+ templates for product descriptions, ad copy, email sequences, and landing pages.", url: "https://copy.ai", tags: ["Copywriting", "Templates", "Marketing"], score: 32 },
      { name: "Writesonic", description: "AI writing assistant that creates SEO-optimized articles, product descriptions, and ad creatives with real-time data.", url: "https://writesonic.com", tags: ["SEO", "Articles", "Ads"], score: 33 },
      { name: "Sudowrite", description: "AI co-writer designed for fiction — brainstorms plot ideas, rewrites scenes, and expands your prose in your own voice.", url: "https://sudowrite.com", tags: ["Fiction", "Creative", "Co-writer"], score: 31, logoUrl: "https://sudowrite.com/favicon.ico" },
      { name: "NovelAI", description: "AI storytelling tool that lets you write, continue, and collaborate on fiction with a powerful language model fine-tuned on literature.", url: "https://novelai.net", tags: ["Fiction", "Storytelling", "Literature"], score: 29, logoUrl: "https://novelai.net/favicon.ico" },
      { name: "Lex", description: "AI-powered word processor that unblocks your writing with suggestions, completions, and a clean distraction-free interface.", url: "https://lex.page", tags: ["Writing", "Focused", "Suggestions"], score: 28, logoUrl: "https://lex.page/favicon.ico" },
      { name: "Rytr", description: "Affordable AI writing assistant with 40+ use cases and 30+ languages — blog posts, emails, product descriptions, and more.", url: "https://rytr.me", tags: ["Affordable", "Multilingual", "Templates"], score: 28 },
      { name: "Grammarly", description: "AI writing assistant that corrects grammar, rewrites sentences for clarity, and adjusts tone — everywhere you write.", url: "https://grammarly.com", tags: ["Grammar", "Clarity", "Tone"], score: 33 },
    ],
  },
  {
    slug: "browser-computer-use",
    label: "Browser & Computer Use",
    desc: "AI agents that control your browser and desktop to complete tasks autonomously — like a human operator.",
    group: "people",
    count: 6,
    tools: [
      { name: "Operator by OpenAI", description: "OpenAI's web browsing agent — navigates websites, fills forms, makes purchases, and completes multi-step browser tasks.", url: "https://openai.com/operator", tags: ["Browser", "Autonomous", "Forms"], score: 35, logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/120px-ChatGPT_logo.svg.png" },
      { name: "Claude Computer Use", description: "Anthropic's computer-use capability that lets Claude see your screen and control mouse and keyboard to complete any desktop task.", url: "https://anthropic.com", tags: ["Desktop", "Screen", "Autonomous"], score: 34, logoUrl: "https://claude.ai/favicon.ico" },
      { name: "MultiOn", description: "Personal AI agent that operates your browser — books appointments, fills forms, extracts data, and handles web-based workflows.", url: "https://multion.ai", tags: ["Browser", "Personal", "Automation"], score: 32, logoUrl: "https://multion.ai/favicon.ico" },
      { name: "Browserbase", description: "Cloud-based browser infrastructure for AI agents — reliable headless browsers with stealth, session management, and replay.", url: "https://browserbase.com", tags: ["Infrastructure", "Headless", "Cloud"], score: 30, logoUrl: "https://browserbase.com/favicon.ico" },
      { name: "Browse AI", description: "No-code tool to train robots to scrape and monitor any website — extract data, track changes, and trigger workflows.", url: "https://browse.ai", tags: ["Scraping", "No-code", "Monitoring"], score: 29, logoUrl: "https://browse.ai/favicon.ico" },
      { name: "Rabbit R1", description: "Dedicated AI hardware and LAM (Large Action Model) that learns to operate apps and websites on your behalf.", url: "https://rabbit.tech", tags: ["Hardware", "LAM", "Consumer"], score: 27, logoUrl: "https://rabbit.tech/favicon.ico" },
    ],
  },
  {
    slug: "research-deep-analysis",
    label: "Research & Deep Analysis",
    desc: "AI agents for deep research, fact-finding, literature review, and synthesis across large knowledge bases.",
    group: "people",
    count: 7,
    tools: [
      { name: "Perplexity AI", description: "Real-time AI search that reads the web and synthesizes cited answers — the fastest way to research any topic.", url: "https://perplexity.ai", tags: ["Search", "Real-time", "Citations"], score: 35, logoUrl: "https://www.perplexity.ai/favicon.ico" },
      { name: "Elicit", description: "AI research assistant that searches academic papers, extracts key findings, and summarizes literature for any research question.", url: "https://elicit.com", tags: ["Academic", "Papers", "Synthesis"], score: 33, logoUrl: "https://elicit.com/favicon.ico" },
      { name: "Consensus", description: "AI-powered search engine for scientific research — finds and distills evidence from 200M+ academic papers.", url: "https://consensus.app", tags: ["Science", "Evidence", "Academic"], score: 32, logoUrl: "https://consensus.app/favicon.ico" },
      { name: "Scite", description: "AI tool that shows how scientific papers have been cited — whether supported, contradicted, or mentioned by later research.", url: "https://scite.ai", tags: ["Citations", "Science", "Credibility"], score: 31, logoUrl: "https://scite.ai/favicon.ico" },
      { name: "ResearchRabbit", description: "AI-powered literature mapping tool that visualizes paper networks and surfaces related research you might have missed.", url: "https://researchrabbit.ai", tags: ["Literature", "Mapping", "Discovery"], score: 30, logoUrl: "https://www.researchrabbit.ai/favicon.ico" },
      { name: "Semantic Scholar", description: "Free AI-powered research tool from Allen Institute that surfaces the most influential papers and authors in any field.", url: "https://semanticscholar.org", tags: ["Free", "Academic", "Influence"], score: 29, logoUrl: "https://www.semanticscholar.org/img/favicon.png" },
      { name: "GPT Researcher", description: "Open-source autonomous research agent that conducts deep online research and produces detailed reports with citations.", url: "https://github.com/assafelovic/gpt-researcher", tags: ["Open Source", "Autonomous", "Reports"], score: 31, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
    ],
  },
  {
    slug: "learning-education",
    label: "Learning & Education",
    desc: "AI tutors, study assistants, and learning companions where education is the primary purpose.",
    group: "people",
    count: 8,
    tools: [
      { name: "Khanmigo", description: "Socratic AI tutor from Khan Academy that guides students through problems with questions rather than just giving answers.", url: "https://khanacademy.org", tags: ["Tutor", "K-12", "Socratic"], score: 34 },
      { name: "Duolingo Max", description: "AI-powered tier of Duolingo with roleplay conversations and Explain My Answer — powered by GPT-4.", url: "https://duolingo.com", tags: ["Languages", "Gamified", "Roleplay"], score: 33, logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Duolingo_logo.svg/120px-Duolingo_logo.svg.png" },
      { name: "Synthesis", description: "AI-powered learning platform that teaches math and critical thinking through collaborative problem-solving games.", url: "https://synthesis.com", tags: ["Math", "Games", "K-12"], score: 32, logoUrl: "https://synthesis.com/favicon.ico" },
      { name: "Coursera", description: "AI-enhanced courses with personalized coaching, real-time feedback on assignments, and adaptive learning paths.", url: "https://coursera.org", tags: ["Courses", "Certificates", "Adaptive"], score: 31 },
      { name: "Quizlet", description: "AI study tool that auto-generates flashcards, practice tests, and personalized study plans from any content.", url: "https://quizlet.com", tags: ["Flashcards", "Tests", "Study"], score: 30 },
      { name: "Socratic by Google", description: "Google's AI homework helper for students — explains concepts, shows worked examples, and links to resources.", url: "https://socratic.org", tags: ["Homework", "Explanations", "Free"], score: 29, logoUrl: "https://socratic.org/favicon.ico" },
      { name: "Photomath", description: "AI math solver that explains step-by-step solutions using your camera — from arithmetic to calculus.", url: "https://photomath.com", tags: ["Math", "Camera", "Step-by-step"], score: 30 },
      { name: "Speak", description: "AI language tutor that gives real-time spoken feedback on pronunciation and fluency — like a native-speaker coach.", url: "https://speak.com", tags: ["Language", "Speaking", "Pronunciation"], score: 31 },
    ],
  },
  {
    slug: "health-wellness",
    label: "Health & Wellness",
    desc: "AI for fitness, mental health, nutrition, medical guidance, and overall wellbeing.",
    group: "people",
    count: 9,
    tools: [
      { name: "Woebot", description: "AI mental health chatbot using CBT techniques to help with anxiety, depression, and emotional regulation — available 24/7.", url: "https://woebothealth.com", tags: ["Mental health", "CBT", "24/7"], score: 32, logoUrl: "https://woebothealth.com/favicon.ico" },
      { name: "Wysa", description: "AI emotional support companion with evidence-based exercises for stress, anxiety, and low mood.", url: "https://wysa.com", tags: ["Emotional support", "Anxiety", "CBT"], score: 31, logoUrl: "https://wysa.com/favicon.ico" },
      { name: "Ada Health", description: "AI symptom assessment app that asks smart questions and helps you understand your health concerns before seeing a doctor.", url: "https://ada.com", tags: ["Symptoms", "Medical", "Triage"], score: 33 },
      { name: "Noom", description: "AI-powered weight management program that combines psychology, nutrition coaching, and behavioral science.", url: "https://noom.com", tags: ["Weight loss", "Nutrition", "Psychology"], score: 30 },
      { name: "WHOOP", description: "AI health coach integrated with WHOOP wearable that analyzes recovery, sleep, and strain to optimize performance.", url: "https://whoop.com", tags: ["Wearable", "Recovery", "Performance"], score: 32 },
      { name: "Calm", description: "AI personalization layer in the Calm app that recommends meditations, sleep stories, and breathing exercises based on your mood.", url: "https://calm.com", tags: ["Meditation", "Sleep", "Mindfulness"], score: 29 },
      { name: "Zing Coach", description: "AI personal trainer that creates adaptive workout plans, tracks form via camera, and adjusts as you progress.", url: "https://zingcoach.com", tags: ["Fitness", "Workouts", "Adaptive"], score: 30, logoUrl: "https://zingcoach.com/favicon.ico" },
      { name: "Lark Health", description: "CDC-recognized AI health coach for diabetes prevention and chronic disease management — text-based, always on.", url: "https://lark.com", tags: ["Diabetes", "Chronic disease", "Coaching"], score: 31 },
    ],
  },

  // ── FOR TEAMS ───────────────────────────────────────────────────────────────
  {
    slug: "sales-marketing",
    label: "Sales & Marketing",
    desc: "AI agents for lead generation, outbound, content marketing, and campaign automation.",
    group: "teams",
    count: 20,
    tools: [
      { name: "Clay", description: "AI data enrichment and outbound platform — pulls data from 50+ sources and writes personalized cold emails at scale.", url: "https://clay.com", tags: ["Enrichment", "Outbound", "Personalization"], score: 36 },
      { name: "Apollo.io", description: "All-in-one sales intelligence platform with AI email writing, sequence automation, and a 275M+ contact database.", url: "https://apollo.io", tags: ["Prospecting", "Sequences", "Database"], score: 35 },
      { name: "Outreach", description: "AI-powered sales execution platform with smart sequence suggestions, deal health scores, and revenue forecasting.", url: "https://outreach.io", tags: ["Sequences", "Forecasting", "Enterprise"], score: 34 },
      { name: "6sense", description: "AI revenue intelligence platform that identifies in-market accounts and prioritizes outreach using buying signals.", url: "https://6sense.com", tags: ["Intent data", "ABM", "Revenue"], score: 34 },
      { name: "Lavender", description: "AI email coach that scores your cold emails in real time and suggests improvements to increase reply rates.", url: "https://lavender.ai", tags: ["Email", "Coaching", "Cold outreach"], score: 32, logoUrl: "https://lavender.ai/favicon.ico" },
      { name: "Jasper", description: "Enterprise AI content platform that generates on-brand marketing copy, blog posts, and ad creatives at scale.", url: "https://jasper.ai", tags: ["Content", "Brand voice", "Marketing"], score: 33 },
      { name: "Drift", description: "AI-powered conversational marketing platform that qualifies leads with chatbots and routes them to the right rep instantly.", url: "https://drift.com", tags: ["Chatbot", "Conversational", "Lead routing"], score: 32 },
      { name: "Persado", description: "AI platform that uses emotional language analysis to generate high-performing ad copy and marketing messages.", url: "https://persado.com", tags: ["Language AI", "Ads", "Emotion"], score: 31 },
    ],
  },
  {
    slug: "customer-support",
    label: "Customer Support",
    desc: "AI-powered support agents, help desk automation, and customer service intelligence.",
    group: "teams",
    count: 13,
    tools: [
      { name: "Intercom Fin", description: "GPT-4-powered AI support agent that resolves 50%+ of support queries instantly using your knowledge base.", url: "https://intercom.com/fin", tags: ["Resolves tickets", "GPT-4", "Knowledge base"], score: 36 },
      { name: "Zendesk AI", description: "AI layer across Zendesk suite — intent detection, auto-tagging, suggested replies, and autonomous ticket resolution.", url: "https://zendesk.com/ai", tags: ["Auto-triage", "Suggestions", "Enterprise"], score: 35 },
      { name: "Freshdesk Freddy AI", description: "Freshworks' AI engine that predicts ticket fields, automates responses, and provides agents with answer suggestions.", url: "https://freshdesk.com", tags: ["Predictions", "Automation", "SMB"], score: 33 },
      { name: "Ada", description: "No-code AI customer service automation platform that resolves inquiries across web, app, and messaging channels.", url: "https://ada.cx", tags: ["No-code", "Multi-channel", "Automation"], score: 34, logoUrl: "https://ada.cx/favicon.ico" },
      { name: "Forethought", description: "Generative AI for customer support that triages tickets, predicts CSAT, and generates agent responses automatically.", url: "https://forethought.ai", tags: ["Triage", "CSAT", "Generative AI"], score: 33, logoUrl: "https://forethought.ai/favicon.ico" },
      { name: "Tidio", description: "AI chatbot and live chat platform for SMBs — Lyro AI resolves up to 70% of common questions autonomously.", url: "https://tidio.com", tags: ["SMB", "Chatbot", "Live chat"], score: 31 },
      { name: "Kustomer", description: "AI-first CRM for customer service teams with automated conversations, proactive support, and rich customer timelines.", url: "https://kustomer.com", tags: ["CRM", "Proactive", "Timelines"], score: 32 },
      { name: "Hiver", description: "AI helpdesk built on Gmail that auto-assigns emails, suggests replies, and gives analytics on shared inbox performance.", url: "https://hiverhq.com", tags: ["Gmail", "Shared inbox", "Auto-assign"], score: 31, logoUrl: "https://hiverhq.com/favicon.ico" },
    ],
  },
  {
    slug: "engineering-devtools",
    label: "Engineering & DevTools",
    desc: "AI coding assistants, code review tools, CI/CD intelligence, and developer productivity solutions for teams.",
    group: "teams",
    count: 13,
    tools: [
      { name: "GitHub Copilot", description: "Team-level AI coding assistant with organization-wide policy controls, audit logs, and IP indemnification.", url: "https://github.com/features/copilot", tags: ["Enterprise", "IDE", "Policy"], score: 35, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
      { name: "Cursor", description: "AI-first code editor with codebase-wide context, autonomous multi-file editing, and PR-level change generation.", url: "https://cursor.sh", tags: ["Editor", "Multi-file", "Codebase"], score: 36, logoUrl: "https://cursor.sh/brand/icon.svg" },
      { name: "Devin", description: "Autonomous AI software engineer that plans, codes, tests, and deploys features end-to-end in a sandboxed environment.", url: "https://devin.ai", tags: ["Autonomous", "SWE", "Full-cycle"], score: 36, logoUrl: "https://devin.ai/favicon.ico" },
      { name: "Linear AI", description: "AI features inside Linear that write issue descriptions, suggest priorities, and auto-create sub-issues from specs.", url: "https://linear.app", tags: ["Project mgmt", "Issues", "Priorities"], score: 33 },
      { name: "Sentry AI", description: "AI-powered error monitoring that auto-triages issues, identifies root causes, and suggests fixes in your codebase.", url: "https://sentry.io", tags: ["Errors", "Root cause", "Monitoring"], score: 34 },
      { name: "Datadog AI", description: "Bits AI inside Datadog that investigates incidents, explains alerts in plain English, and suggests remediation steps.", url: "https://datadoghq.com", tags: ["Observability", "Incidents", "Monitoring"], score: 33 },
      { name: "Snyk", description: "AI security assistant that finds and fixes vulnerabilities in code, containers, IaC, and open source dependencies.", url: "https://snyk.io", tags: ["Security", "Vulnerabilities", "DevSecOps"], score: 34 },
      { name: "Trunk", description: "AI code quality platform with automated code review, merge queue, and CI analytics for engineering teams.", url: "https://trunk.io", tags: ["Code review", "CI", "Quality"], score: 31, logoUrl: "https://trunk.io/favicon.ico" },
    ],
  },
  {
    slug: "data-analytics",
    label: "Data & Analytics",
    desc: "AI for data analysis, business intelligence, natural language querying, and automated reporting.",
    group: "teams",
    count: 14,
    tools: [
      { name: "Julius AI", description: "AI data analyst that connects to your data, writes and runs Python/SQL, creates charts, and explains findings in plain English.", url: "https://julius.ai", tags: ["Python", "SQL", "Charts"], score: 35, logoUrl: "https://julius.ai/favicon.ico" },
      { name: "Akkio", description: "No-code AI analytics platform for agencies and teams — build predictive models and dashboards from CSV or CRM data.", url: "https://akkio.com", tags: ["No-code", "Predictive", "Agencies"], score: 32, logoUrl: "https://akkio.com/favicon.ico" },
      { name: "Obviously AI", description: "No-code predictive AI that builds machine learning models from your spreadsheet data in minutes.", url: "https://obviously.ai", tags: ["No-code", "ML", "Predictions"], score: 31, logoUrl: "https://obviously.ai/favicon.ico" },
      { name: "Rows", description: "AI-powered spreadsheet that writes formulas, summarizes data, and generates charts from natural language prompts.", url: "https://rows.com", tags: ["Spreadsheet", "Formulas", "Charts"], score: 32 },
      { name: "Polymer", description: "AI data storytelling tool that turns spreadsheets into interactive dashboards without writing a single line of code.", url: "https://polymersearch.com", tags: ["Dashboards", "No-code", "Stories"], score: 30, logoUrl: "https://polymersearch.com/favicon.ico" },
      { name: "DataRobot", description: "Enterprise AI platform for automated machine learning — builds, deploys, and monitors predictive models at scale.", url: "https://datarobot.com", tags: ["AutoML", "Enterprise", "MLOps"], score: 34 },
      { name: "Hex", description: "Collaborative data notebook with AI that writes SQL and Python, then turns analysis into shareable apps.", url: "https://hex.tech", tags: ["Notebooks", "SQL", "Collaboration"], score: 33, logoUrl: "https://hex.tech/favicon.ico" },
      { name: "ThoughtSpot", description: "AI-powered analytics platform with natural language search across your data warehouse — ask questions, get instant answers.", url: "https://thoughtspot.com", tags: ["NL search", "Warehouse", "Enterprise"], score: 33 },
    ],
  },
  {
    slug: "workflow-automation",
    label: "Workflow Automation",
    desc: "General-purpose workflow automation platforms that connect apps, trigger actions, and run AI-powered processes.",
    group: "teams",
    count: 13,
    tools: [
      { name: "Zapier", description: "The most popular automation platform with 6,000+ app integrations — connect any apps and automate workflows without code.", url: "https://zapier.com", tags: ["No-code", "6000+ apps", "Triggers"], score: 34 },
      { name: "Make", description: "Visual automation builder with advanced data routing, error handling, and complex multi-step workflow design.", url: "https://make.com", tags: ["Visual", "Advanced", "Routing"], score: 33 },
      { name: "n8n", description: "Open-source workflow automation with self-hosting option — 400+ integrations and full code access for advanced use cases.", url: "https://n8n.io", tags: ["Open Source", "Self-hosted", "Code"], score: 34 },
      { name: "Activepieces", description: "Open-source Zapier alternative with a clean UI, AI steps built-in, and self-hosting for data-sensitive teams.", url: "https://activepieces.com", tags: ["Open Source", "Self-hosted", "AI steps"], score: 32, logoUrl: "https://activepieces.com/favicon.ico" },
      { name: "Relay.app", description: "Human-in-the-loop automation platform that blends AI steps with manual approval gates for sensitive workflows.", url: "https://relay.app", tags: ["Human-in-loop", "AI steps", "Approvals"], score: 31, logoUrl: "https://relay.app/favicon.ico" },
      { name: "Bardeen", description: "AI automation platform for browser workflows — scrapes, transforms, and syncs data across web apps without switching tabs.", url: "https://bardeen.ai", tags: ["Browser", "Scraping", "No-code"], score: 30, logoUrl: "https://bardeen.ai/favicon.ico" },
      { name: "Tray.io", description: "Enterprise iPaaS with AI-assisted workflow building — handles complex data transformations and high-volume automations.", url: "https://tray.io", tags: ["Enterprise", "iPaaS", "Complex"], score: 32 },
      { name: "Workato", description: "Enterprise automation platform combining integration, AI, and workflow orchestration across cloud and on-premise systems.", url: "https://workato.com", tags: ["Enterprise", "Integration", "On-premise"], score: 33 },
    ],
  },
  {
    slug: "agent-frameworks-orchestration",
    label: "Agent Frameworks & Orchestration",
    desc: "Open-source frameworks and SDKs for building, orchestrating, and deploying custom AI agents.",
    group: "teams",
    count: 13,
    tools: [
      { name: "LangChain", description: "The most popular open-source framework for building LLM-powered apps and agents with chains, tools, and memory.", url: "https://langchain.com", tags: ["Open Source", "Python", "Popular"], score: 35 },
      { name: "AutoGen", description: "Microsoft's multi-agent conversation framework — multiple AI agents collaborate, debate, and solve problems together.", url: "https://microsoft.github.io/autogen", tags: ["Multi-agent", "Microsoft", "Open Source"], score: 34, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
      { name: "CrewAI", description: "Framework for orchestrating role-based AI agents — define a crew with specialized roles and let them collaborate on tasks.", url: "https://crewai.com", tags: ["Role-based", "Collaboration", "Open Source"], score: 35, logoUrl: "https://crewai.com/favicon.ico" },
      { name: "LlamaIndex", description: "Data framework for LLM apps — indexes, retrieves, and queries your private data for RAG pipelines and agents.", url: "https://llamaindex.ai", tags: ["RAG", "Data", "Indexing"], score: 33, logoUrl: "https://llamaindex.ai/favicon.ico" },
      { name: "Haystack", description: "Production-ready NLP framework for building search, QA systems, and conversational AI pipelines.", url: "https://haystack.deepset.ai", tags: ["NLP", "Search", "Production"], score: 32, logoUrl: "https://haystack.deepset.ai/favicon.ico" },
      { name: "Semantic Kernel", description: "Microsoft's SDK for integrating LLMs into .NET, Python, and Java applications with a plugin architecture.", url: "https://github.com/microsoft/semantic-kernel", tags: ["Microsoft", ".NET", "Plugins"], score: 31, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
      { name: "LangGraph", description: "LangChain's framework for building stateful, cyclical multi-agent workflows with fine-grained control flow.", url: "https://langchain-ai.github.io/langgraph", tags: ["Stateful", "Cyclical", "Control flow"], score: 33, logoUrl: "https://langchain.com/favicon.ico" },
      { name: "OpenAI Swarm", description: "OpenAI's lightweight multi-agent framework focused on handoffs between specialized agents for complex tasks.", url: "https://github.com/openai/swarm", tags: ["OpenAI", "Handoffs", "Lightweight"], score: 32, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
    ],
  },
  {
    slug: "agent-infrastructure",
    label: "Agent Infrastructure",
    desc: "The plumbing layer for AI agents: memory, tool integrations, observability, sandboxing, and identity management.",
    group: "teams",
    count: 21,
    tools: [
      { name: "E2B", description: "Secure cloud sandboxes for AI agents — run AI-generated code safely in isolated environments with full observability.", url: "https://e2b.dev", tags: ["Sandboxing", "Code execution", "Security"], score: 34, logoUrl: "https://e2b.dev/favicon.ico" },
      { name: "Composio", description: "Tool integration platform for AI agents — 250+ pre-built integrations (CRMs, email, calendar, code) ready for any agent.", url: "https://composio.dev", tags: ["Integrations", "250+ tools", "Connectors"], score: 35, logoUrl: "https://composio.dev/favicon.ico" },
      { name: "Mem0", description: "Memory layer for AI agents — persistent, adaptive memory that improves agent performance across sessions.", url: "https://mem0.ai", tags: ["Memory", "Persistent", "Adaptive"], score: 33, logoUrl: "https://mem0.ai/favicon.ico" },
      { name: "Weaviate", description: "Open-source vector database for AI agents — stores and retrieves embeddings for RAG, memory, and semantic search.", url: "https://weaviate.io", tags: ["Vector DB", "Open Source", "RAG"], score: 33 },
      { name: "Pinecone", description: "Managed vector database that powers semantic search and long-term memory for production AI agents.", url: "https://pinecone.io", tags: ["Vector DB", "Managed", "Production"], score: 34 },
      { name: "LangSmith", description: "LangChain's observability platform for LLM apps — trace, debug, evaluate, and monitor agent runs in production.", url: "https://smith.langchain.com", tags: ["Observability", "Tracing", "Evaluation"], score: 33, logoUrl: "https://langchain.com/favicon.ico" },
      { name: "Helicone", description: "Open-source LLM observability tool that logs every request, tracks costs, and monitors latency across providers.", url: "https://helicone.ai", tags: ["Logging", "Costs", "Observability"], score: 31, logoUrl: "https://helicone.ai/favicon.ico" },
      { name: "Browserbase", description: "Cloud browser infrastructure for AI agents — reliable, stealthy headless browsers with session management.", url: "https://browserbase.com", tags: ["Browser", "Headless", "Cloud"], score: 32, logoUrl: "https://browserbase.com/favicon.ico" },
    ],
  },
  {
    slug: "enterprise-agent-platforms",
    label: "Enterprise Agent Platforms",
    desc: "Full-stack platforms for deploying AI agents at organizational scale with governance and compliance.",
    group: "teams",
    count: 19,
    tools: [
      { name: "Microsoft Copilot Studio", description: "Microsoft's enterprise agent builder — create custom Copilot agents with your data, integrated across Microsoft 365.", url: "https://microsoft.com/copilot-studio", tags: ["Microsoft", "M365", "No-code"], score: 35, logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/120px-Microsoft_logo.svg.png" },
      { name: "Salesforce Agentforce", description: "Salesforce's autonomous agent platform that takes action across CRM, service, sales, and commerce workflows.", url: "https://salesforce.com/agentforce", tags: ["Salesforce", "CRM", "Autonomous"], score: 36 },
      { name: "ServiceNow AI Agents", description: "AI agents built into the ServiceNow platform that autonomously handle IT, HR, and customer service workflows.", url: "https://servicenow.com", tags: ["ITSM", "HR", "Enterprise"], score: 34 },
      { name: "SAP AI Core", description: "SAP's AI platform for running and managing AI workloads across SAP applications with enterprise-grade controls.", url: "https://sap.com/ai", tags: ["SAP", "Enterprise", "MLOps"], score: 33 },
      { name: "IBM watsonx", description: "IBM's AI agent platform that automates repetitive tasks across enterprise apps using skills and an assistant builder.", url: "https://ibm.com/watsonx", tags: ["IBM", "Enterprise", "Skills"], score: 33 },
      { name: "UiPath Autopilot", description: "AI agent capabilities inside UiPath's RPA platform — combine AI and robotic automation for end-to-end process automation.", url: "https://uipath.com", tags: ["RPA", "Process automation", "Enterprise"], score: 34 },
      { name: "Automation Anywhere", description: "Enterprise AI agents that combine RPA, AI, and process intelligence for complex business workflows.", url: "https://automationanywhere.com", tags: ["RPA", "AI", "Enterprise"], score: 33 },
      { name: "Moveworks", description: "Enterprise AI agent platform that automates IT, HR, and finance support — resolves employee requests across any system.", url: "https://moveworks.com", tags: ["IT support", "HR", "Employee"], score: 34 },
    ],
  },
  {
    slug: "research-intelligence",
    label: "Research & Intelligence",
    desc: "AI for market research, competitive intelligence, deep analysis, and knowledge synthesis at a business level.",
    group: "teams",
    count: 9,
    tools: [
      { name: "Crayon", description: "Competitive intelligence platform that tracks competitors across 100+ data sources and alerts teams to market changes in real time.", url: "https://crayon.co", tags: ["Competitive intel", "Tracking", "Alerts"], score: 33, logoUrl: "https://crayon.co/favicon.ico" },
      { name: "Klue", description: "AI-powered competitor tracking that turns competitive data into battle cards and sales enablement content.", url: "https://klue.com", tags: ["Battle cards", "Sales enablement", "Competitors"], score: 32 },
      { name: "AlphaSense", description: "Enterprise market intelligence platform with AI search across earnings calls, research reports, and news.", url: "https://alpha-sense.com", tags: ["Finance", "Earnings", "Enterprise"], score: 34, logoUrl: "https://alpha-sense.com/favicon.ico" },
      { name: "Similarweb", description: "Digital intelligence platform with AI analysis of website traffic, market share, and competitive benchmarking.", url: "https://similarweb.com", tags: ["Traffic", "Benchmarking", "Digital"], score: 33 },
      { name: "Perplexity Pro", description: "Team-level research AI with shared spaces, source-cited answers, and enterprise privacy controls.", url: "https://perplexity.ai/pro", tags: ["Teams", "Research", "Citations"], score: 34, logoUrl: "https://www.perplexity.ai/favicon.ico" },
      { name: "Consensus", description: "AI-powered scientific literature search for enterprise research and R&D teams — evidence-based answers at scale.", url: "https://consensus.app", tags: ["Science", "R&D", "Evidence"], score: 31, logoUrl: "https://consensus.app/favicon.ico" },
      { name: "Exploding Topics", description: "AI that scans the internet for rapidly growing topics before they become mainstream — for market research and trend spotting.", url: "https://explodingtopics.com", tags: ["Trends", "Market research", "Discovery"], score: 30 },
      { name: "Brandwatch", description: "Consumer intelligence and social listening platform with AI to analyze billions of online conversations.", url: "https://brandwatch.com", tags: ["Social listening", "Consumer", "Intelligence"], score: 32 },
    ],
  },
  {
    slug: "voice-phone-agents",
    label: "Voice & Phone Agents",
    desc: "AI agents for inbound and outbound voice calls, phone automation, and conversational voice interfaces.",
    group: "teams",
    count: 12,
    tools: [
      { name: "Bland AI", description: "AI phone calling platform that makes and receives calls at scale — book appointments, qualify leads, and handle support calls.", url: "https://bland.ai", tags: ["Calls", "Outbound", "Inbound"], score: 35, logoUrl: "https://bland.ai/favicon.ico" },
      { name: "Vapi", description: "Developer platform for building voice AI agents — ultra-low latency, custom voices, and tool calling during live calls.", url: "https://vapi.ai", tags: ["Developers", "Low latency", "Tool calling"], score: 35, logoUrl: "https://vapi.ai/favicon.ico" },
      { name: "Retell AI", description: "Voice AI platform for building conversational phone agents with natural turn-taking, interruption handling, and CRM sync.", url: "https://retellai.com", tags: ["Conversational", "Natural", "CRM sync"], score: 34, logoUrl: "https://retellai.com/favicon.ico" },
      { name: "ElevenLabs", description: "AI voice synthesis platform with ultra-realistic voices — powers voice AI agents with cloning, multilingual support, and streaming.", url: "https://elevenlabs.io", tags: ["Voice synthesis", "Cloning", "Multilingual"], score: 34 },
      { name: "Synthflow", description: "No-code voice AI agent builder — set up AI phone agents for inbound and outbound calls without any engineering.", url: "https://synthflow.ai", tags: ["No-code", "Inbound", "Outbound"], score: 32, logoUrl: "https://synthflow.ai/favicon.ico" },
      { name: "Vocode", description: "Open-source library for building voice AI agents in Python — handles transcription, LLM calls, and synthesis in real time.", url: "https://vocode.dev", tags: ["Open Source", "Python", "Real-time"], score: 31, logoUrl: "https://vocode.dev/favicon.ico" },
      { name: "Air AI", description: "AI phone agent that has full 10-40 minute conversations with customers, remembers context, and takes real-world actions.", url: "https://air.ai", tags: ["Long calls", "Memory", "Actions"], score: 33, logoUrl: "https://air.ai/favicon.ico" },
      { name: "Deepgram", description: "AI speech platform with best-in-class real-time transcription — the infrastructure layer powering many voice AI agents.", url: "https://deepgram.com", tags: ["Transcription", "Real-time", "Infrastructure"], score: 33 },
    ],
  },
  {
    slug: "browser-automation-agents",
    label: "Browser Automation Agents",
    desc: "AI agents that autonomously browse the web, interact with websites, fill forms, and extract data.",
    group: "teams",
    count: 8,
    tools: [
      { name: "Browse AI", description: "Train robots to scrape and monitor any website without code — extracts structured data and triggers workflows on changes.", url: "https://browse.ai", tags: ["Scraping", "No-code", "Monitoring"], score: 32, logoUrl: "https://browse.ai/favicon.ico" },
      { name: "Apify", description: "Cloud platform for web scraping and browser automation — 1,500+ pre-built scrapers and a robust actor-based architecture.", url: "https://apify.com", tags: ["Scraping", "Cloud", "Actors"], score: 33 },
      { name: "Browserbase", description: "Reliable cloud browser infrastructure for AI agents with stealth, session replay, and live debugging.", url: "https://browserbase.com", tags: ["Infrastructure", "Stealth", "Reliable"], score: 32, logoUrl: "https://browserbase.com/favicon.ico" },
      { name: "MultiOn", description: "AI agent that operates browsers on your behalf — books restaurants, fills out forms, and handles multi-step web tasks.", url: "https://multion.ai", tags: ["Autonomous", "Personal", "Tasks"], score: 31, logoUrl: "https://multion.ai/favicon.ico" },
      { name: "Playwright", description: "Microsoft's open-source browser automation library — powers many AI browser agents with cross-browser support.", url: "https://playwright.dev", tags: ["Open Source", "Microsoft", "Cross-browser"], score: 30, logoUrl: "https://playwright.dev/img/playwright-logo.svg" },
      { name: "Bright Data", description: "Enterprise web data platform with residential proxies, browser API, and datasets for web automation at scale.", url: "https://brightdata.com", tags: ["Enterprise", "Proxies", "Scale"], score: 32 },
      { name: "Hyperbrowser", description: "AI-native browser API designed for agents — instant sessions, built-in stealth, and a computer-use API.", url: "https://hyperbrowser.ai", tags: ["AI-native", "Stealth", "Instant"], score: 30, logoUrl: "https://hyperbrowser.ai/favicon.ico" },
      { name: "Firecrawl", description: "Turn any website into LLM-ready structured data — crawl, scrape, and extract content for AI pipelines.", url: "https://firecrawl.dev", tags: ["LLM-ready", "Crawl", "Structured"], score: 31, logoUrl: "https://firecrawl.dev/favicon.ico" },
    ],
  },
  {
    slug: "multi-agent-orchestration",
    label: "Multi-Agent Orchestration",
    desc: "Frameworks and platforms for coordinating multiple specialized AI agents working together on complex tasks.",
    group: "teams",
    count: 7,
    tools: [
      { name: "CrewAI", description: "Define a crew of AI agents with specialized roles — researcher, writer, analyst — and let them collaborate autonomously.", url: "https://crewai.com", tags: ["Role-based", "Collaboration", "Open Source"], score: 35, logoUrl: "https://crewai.com/favicon.ico" },
      { name: "AutoGen", description: "Multi-agent conversation framework where agents discuss, critique, and refine solutions together.", url: "https://microsoft.github.io/autogen", tags: ["Conversation", "Microsoft", "Open Source"], score: 34, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
      { name: "LangGraph", description: "Build stateful multi-agent workflows as graphs — precise control over agent handoffs and cyclic reasoning loops.", url: "https://langchain-ai.github.io/langgraph", tags: ["Graphs", "Stateful", "Handoffs"], score: 34, logoUrl: "https://langchain.com/favicon.ico" },
      { name: "MetaGPT", description: "Multi-agent framework that simulates a software company — product manager, engineer, QA all collaborate on coding tasks.", url: "https://metagpt.com", tags: ["Software company", "Roles", "Coding"], score: 32, logoUrl: "https://metagpt.com/favicon.ico" },
      { name: "AgentVerse", description: "Multi-agent simulation framework for collaborative problem-solving and benchmarking agent communication strategies.", url: "https://github.com/OpenBMB/AgentVerse", tags: ["Simulation", "Research", "Benchmarking"], score: 29, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
      { name: "OpenAI Swarm", description: "Lightweight framework by OpenAI for building networks of agents that hand off tasks to specialized sub-agents.", url: "https://github.com/openai/swarm", tags: ["OpenAI", "Handoffs", "Lightweight"], score: 32, logoUrl: "https://github.githubassets.com/favicons/favicon.png" },
      { name: "Vertex AI Agent Builder", description: "Google Cloud's platform for building and orchestrating multi-agent systems with Gemini at enterprise scale.", url: "https://cloud.google.com/products/agent-builder", tags: ["Google Cloud", "Gemini", "Enterprise"], score: 33, logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Google_Cloud_logo.svg/120px-Google_Cloud_logo.svg.png" },
    ],
  },
]

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug)
}

export function generateCategorySlugs() {
  return CATEGORIES.map((c) => ({ category: c.slug }))
}